name: Deploy Flask App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        ssh -o StrictHostKeyChecking=no root@sustainabilityittech.in << EOF
          cd /root/projects/MACC-PROJECT
          git pull origin main

          source venv/bin/activate

          # Inject DATABASE_URL securely from GitHub Secrets
          export DATABASE_URL="${DATABASE_URL}"

          pip install -r requirements.txt

          # Run migrations (Flask-Migrate must be set up)
          flask db upgrade

          # Restart services
          sudo systemctl restart macc_chart_Generator_flask.service
          sudo systemctl reload nginx
        EOF